### ISSUE TITLE
Documentation? How to use?

### ISSUE THREAD

**Issue by geerlingguy** [pygmystack/pygmy-legacy#12]
I'm refining a list of [Drupal Dev Environment Tools](https://docs.google.com/spreadsheets/d/11LWo_ks9TUoZIYJW0voXwogawohqAbOFv_dcBlAVs2E/), and had Lagoon on the list; however someone mentioned that pygmy is the tool used for local environments, while Lagoon is more meant for full-fledged production OpenShift-based environments...

Could you include a readme in this project with at least a link to https://docs.amazee.io/local_docker_development/pygmy.html or some 'getting started' steps? It wasn't obvious when I first started walking through the GitHub projects or the Lagoon documentation where to get pygmy or how to use it.

**Comment by dasrecht** [comment]
Hi @geerlingguy 
sorry your issue wasn't responded to earlier. 

Yes that's correct. Pygmy is basically giving you the tooling around docker to be able to start developing locally.

I've added a bit of context to the repository - https://github.com/amazeeio/pygmy/blob/master/README.md

**Comment by geerlingguy** [comment]
Perfect, thanks!

**Comment by dasrecht** [comment]
Very welcome :)
