### ISSUE TITLE
Example for multiple web-servers in one application

### ISSUE THREAD

**Issue by ghost** [pygmystack/pygmy-legacy#15]
I am trying to setup a local development environment using Lagoon + Pygmy for a web application with a JavaScript frontend and a PHP/Drupal backend. Therefore I started with the [Amazee Drupal Example](https://github.com/amazeeio/drupal-example) and tried to adapt it to my needs, but without success so far.

Ideally I would like a setup similar to the following:
* Frontend on http://webapp.docker.amazee.io/
  - A simple nginx delivering static files would be enough for our use case
* Backend on http://webapp-api.docker.amazee.io/
  - The default setup as laid out in the Amazee Drupal Example would be sufficient (i.e. we do not care much about the specifics, as long as it works)

Do you have an example available for such a setup?

My naive attempt by setting different `LAGOON_ROUTE`s for the frontend and backend services was not successful. My latest problem is that I cannot get the frontend hostname to route to the frontend nginx - I only receive `503 Service Unavailable` instead. Using the `LAGOON_LOCALDEV_URL` instead appears to work.

**Comment by dasrecht** [comment]
Hi @urzds 

We follow that principle with the Decoupled Drupal Project which does exactly what you're looking for - https://github.com/drupal-graphql/drupal-decoupled-app

**Comment by ghost** [comment]
Thanks, Bastian!

I could not figure out how the Drupal decoupled example actually works. You have a `LAGOON_ROUTE` that is set for all containers and the containers communicate among each other using the container-specific `LAGOON_LOCALDEV_URL`. But how does pygmy decide which container to route traffic to the domain specified in `LAGOON_ROUTE` to?

My issue was that while I can reach the backend containers at http://webapp-api.docker.amazee.io/ (they have set `LAGOON_ROUTE=http://webapp-api.docker.amazee.io/`) I get a `503 Service Unavailable` for the frontend container at http://webapp.docker.amazee.io/ (which has set `LAGOON_ROUTE=http://webapp.docker.amazee.io/`). It eludes me how you can set the same `LAGOON_ROUTE` for all containers in the Drupal decoupled example, but still have the traffic for the frontend and backend arrive at the different containers...

I would have looked up the meaning of the various envvars in the documentation, but sadly the [documentation of the Lagoon/Pygmy specifics of docker-compose.yml](https://lagoon.readthedocs.io/en/latest/using_lagoon/#docker-composeyml) only consists of a (very) brief summary.

**Comment by rtprio** [comment]
@urzds:

`LAGOON_ROUTE` is only used when the site is deployed. In this specific example, I believe it needs updated, as routes are now defined in `.lagoon.yml`: https://github.com/amazeeio/drupal-example/blob/master/.lagoon.yml#L36-L38  This allows you to set different urls for different containers.

For local development, you want to use `LAGOON_LOCALDEV_URL`. This variable will inform the docker haproxy of the additional destination.

**Comment by rtprio** [comment]
The specific use of `LAGOON_LOCALDEV_URL` is here: https://github.com/amazeeio/docker-haproxy/blob/master/haproxy.tmpl#L45
