### ISSUE TITLE
Allow SSH keys from the Gnupg keyring to be used

### ISSUE THREAD

**Issue by Neo-Oli** [pygmystack/pygmy-legacy#16]
You can use `gpg-agent` to serve as an ssh-agent. ([simple tutorial](https://ryanlue.com/posts/2017-06-29-gpg-for-ssh-auth)). That way your SSH key is bound to your PGP keyring. With this setup there is no traditional `id_rsa` file and therefore pygmy fails to add the correct key. Ideally there should be a way for me to forward my ssh-agent to the docker enviroment instead of setting up a new one.

**Comment by dasrecht** [comment]
Hi @Neo-Oli thanks for your request.

Pygmy actually does only take the key into a ssh container temporarily without relying on the `ssh-agent` of the host system. The only thing we rely on is the key living on the host system. That way implementing `gpg-agent` would be a bit more complex to accomplish it.

If you see an easy way to implement this into pygmy feel free to open a pull request or ammend this ticket. So far you'd be the first one asking for this feature.

/bastian

**Comment by kmbremner** [comment]
Hi @dasrecht 

I use a YubiKey smartcard to store my ssh keys. This means that I also have no `id_rsa` file locally.

Like @Neo-Oli I would certainly be interested in having pygmy use `ssh-agent` of the local system, rather than having a separate ssh key locally just for use with pygmy.
