### ISSUE TITLE
WSL insecure ssh key

### ISSUE THREAD

**Issue by tnagyce** [pygmystack/pygmy-legacy#17]
Hi,

I've tried to start the pygmy service on Windows with WSL, but I'm getting an insecure ssh key error.

![screen shot 2018-08-02 at 12 21 41](https://user-images.githubusercontent.com/7201339/43578874-80644974-9650-11e8-872b-d6b6f9d9e707.png)

The key's permission is setup properly inside WSL, although seemingly pygmy having issues identifying it properly.

**Comment by tnagyce** [comment]
I've investigated it a little bit further and looks like the issue is not with pygmy itself, but with the shared folder from windows to docker. I guess that's why ssh-add sees it with mod 0755.

**Comment by dasrecht** [comment]
Hi Tamas

Yes this seems to be connected to the permissions of the WSL - There are ways described here: https://github.com/Microsoft/WSL/issues/3530
