### ISSUE TITLE
Provide feature to automatically update Lagoon Images

### ISSUE THREAD

**Issue by Schnitzel** [pygmystack/pygmy-legacy#20]
```
docker image ls --format "{{.Repository}}:{{.Tag}}" | grep amazeeio/ | grep -v none | xargs -n1 docker pull | cat
```

**Comment by fubarhouse** [comment]
I've opened PR #21 to accommodate these changes.

I'm willing and happy to work with you to help here, so any feedback you can provide is appreciated.

edit:

Here's a sample for your convenience.

![image](https://user-images.githubusercontent.com/3070264/46847008-f2f82900-ce2d-11e8-8114-b3efca39f711.png)
