### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by fubarhouse** [pygmystack/pygmy-legacy#23]
Is there a well-documented list of issues associated with support for native Windows support?

Here's what I've put together, but I'm looking to make it a more accurate and complete list.

* Proxy is reported to not work on windows because of the hosts file (?)
* Bash commands baked in are simply not available for use in Cmd/PS
* Resolvr?
* SSH keys?

I've been referred to this for better windows support, but I don't fully understand the scope of its limitations at this time. https://github.com/amazeeio/amazeeio-docker-windows 

Any input to help complete this list would be appreciated.

**Comment by fubarhouse** [comment]
I've actually got pygmy working on Windows; I intend to refine my work a little before submitting a PR.

The changes can be viewed/tested over here:
* https://github.com/amazeeio/pygmy/compare/master...fubarhouse:feature/windows?expand=1

**Comment by AlexSkrypnyk** [comment]
@Schnitzel is there any chance to use AppVeyor as CI for windows? If you can register an account, I can add a PR with Docker setup under windows so that all these Windows-related PRs are throughly tested. This will improve the stability of pygmy and ease the maintenance.

**Comment by Schnitzel** [comment]
@alexdesignworks awesome idea :) I configured AppVeyor for pygmy: https://ci.appveyor.com/project/Schnitzel/pygmy

**Comment by tobybellwood** [comment]
https://github.com/pygmystack/pygmy supports windows
