### ISSUE TITLE
local websites are not working after docker4mac upgrade to 2.1.0.0

### ISSUE THREAD

**Issue by Drupal-onfire84** [pygmystack/pygmy-legacy#41]
Yesterday i installed the upgraded to latest docker4mac (2.1.0.0). Since then i had problems with my local dev environments. Everything looks fine, all containers are up and running, but i can not enter the local websites in browser (tested in FF and chrome). I got a "connection to the server failed" error. Restarted pygmy many times. After that did not help i removed all docker containers and volumes and started again with a fresh build (tried more than once). But this did not help. Now i downgraded to docker4mac 2.0.0.3 and everything works again.

**Comment by fmuellerprevion** [comment]
Also having the same problem.
Docker seems to append to my /etc/hosts file the localhost IP which leads to kubernetes every time we start docker:

![image](https://user-images.githubusercontent.com/26752987/62370321-1661a100-b532-11e9-9ea1-2e35f02b6ed9.png)

VMs won't work even when we remove the kubernetes line, or remove the localhost line, or guide 127.0.0.1 to docker.amazee.io - no changes.

**Comment by dasrecht** [comment]
After a bit of debugging and figuring out things i found the culprit : https://github.com/docker/for-mac/issues/3775

It looks like all ports below 1024 are blocked by docker now. Thus our dns container on port 52 is currently defunct.

Found via : https://github.com/andyshinn/docker-dnsmasq/issues/26

I'll roll a patch for that and release a new pygmy version next week

**Workaround:**
In the meantime you can override the DNS via your local `hosts` file with `127.0.0.1`
