### ISSUE TITLE
Keep docker container names consistent

### ISSUE THREAD

**Issue by wilroboly** [pygmystack/pygmy-legacy#54]
I've noticed, when working with pygmy that the container aliases do not all align:

![image](https://user-images.githubusercontent.com/1234322/103020953-640bee80-4517-11eb-90bd-8a9ae3703b77.png)

If we could get the mailhog container to get a nice prefixed name like the other ones, would be great for filtering.

Much appreciated!

PS: Not sure if anyone really gets the same degree of meticulousness as I do, but could it be called pygmy-* as opposed to amazeeio-* as well? More descriptive of the task that way too.

**Comment by tobybellwood** [comment]
https://github.com/pygmystack/pygmy supports this
