### ISSUE TITLE
improve Resolver config on Ubuntu 20.04

### ISSUE THREAD

**Issue by twardnw** [pygmystack/pygmy-legacy#56]
In Ubuntu 20.04, rather than updating /etc/resolv.conf , a file should be placed at `/etc/systemd/resolved.conf.d` with the contents
```
[Resolve]
DNS=127.0.0.1:6053
Domains=docker.amazee.io
```

**Comment by tobybellwood** [comment]
https://github.com/pygmystack/pygmy supports this
