### ISSUE TITLE
Ubuntu 17.10 ... 0.0.0.0:53: bind: address already in use

### ISSUE THREAD

**Issue by naume** [pygmystack/pygmy-legacy#6]
Since I'm on ubunut 17.10 I've this error and this fix here https://askubuntu.com/questions/233222/how-can-i-disable-the-dns-that-network-manager-uses/233223#233223 is working fine on 16.04 but not on 17.10 
```
Error response from daemon: driver failed programming external connectivity on endpoint amazeeio-dnsmasq (cccb334e24a7c810b31ec5b8297aca8c30ddf7a45b6abaf65201a230e8112536): Error starting userland proxy: listen udp 0.0.0.0:53: bind: address already in use
Error: failed to start containers: amazeeio-dnsmasq
/var/lib/gems/2.3.0/gems/pygmy-0.9.8/lib/pygmy/docker_service.rb:13:in `start': Failed to run amazeeio-dnsmasq.  Command docker run -d -p 53:53/tcp -p 53:53/udp --name=amazeeio-dnsmasq --cap-add=NET_ADMIN andyshinn/dnsmasq:2.75 -A /docker.amazee.io/127.0.0.1 failed (RuntimeError)
	from /var/lib/gems/2.3.0/gems/pygmy-0.9.8/bin/pygmy:120:in `exec_up'
	from /var/lib/gems/2.3.0/gems/pygmy-0.9.8/bin/pygmy:33:in `up'
	from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /var/lib/gems/2.3.0/gems/pygmy-0.9.8/bin/pygmy:300:in `<top (required)>'
	from /usr/local/bin/pygmy:22:in `load'
	from /usr/local/bin/pygmy:22:in `<main>'```

**Comment by bartfeenstra** [comment]
I had the same problem. To work around this, and also because Pygmy intercepting my hosts's DNS resolver caused actual DNS resolving trouble, I created a VM to run Pygmy in: https://github.com/bartfeenstra/pygmy-vm

**Comment by dasrecht** [comment]
I looked at DORY - https://github.com/FreedomBen/dory/blob/00bc95916eb492d26174cc84360ce53cba69f2d2/lib/dory/dnsmasq.rb#L169-L196

Dory implements the handling of the local DNS Resolver while maintaining functionality of the local DNS setup with Ubuntu 17.10

**Comment by jrsouth** [comment]
I have a quick and not TOO dirty workaround:

```
sudo service systemd-resolved stop
sudo nano /etc/resolv.conf
pygmy up
```

(Nano is to edit `/etc/resolv.conf` so that `nameserver 127.0.0.53` becomes `nameserver 127.0.0.1`)

This stops the local DNS resolver and allows pygmy's `dnsmasq` container to take over.

I have to do this once per boot, which is a little painful, but it could be worse.

**Comment by RoSk0** [comment]
I'm running Vagrant with LXC backend for local dev and ran in the same issue. 

I have tweeked gem command to be 
```
docker run -d -p 127.0.0.1:53:53/tcp -p 127.0.0.1:53:53/udp --name=amazeeio-dnsmasq --cap-add=NET_ADMIN andyshinn/dnsmasq:2.75 -A /docker.amazee.io/127.0.0.1
```
to bind to 127.0.0.1 instead of 0.0.0.0 but it still failing.

I'm obviously missing something about port mapping... :(

**Comment by dasrecht** [comment]
I ran across a few Ubuntu 17.10s that completely lost internet connection when trying to use the workaround mentioned above. 
As backporting the feature from dory takes some time i implemented a `--no-resolver` flag which then needs an entry in `/etc/hosts` to make it work. Better than nothing. 

This is currently already on the road to be released with version 0.9.9 - https://github.com/amazeeio/pygmy/pull/9

**Comment by RoSk0** [comment]
I think something went wrong with my testing last time and providing IP address explicitly actually fixes the issue, so pull request provided.

**Comment by ghost** [comment]
Same issue when using libvirtd, which is installed and enabled by default on Fedora 28 in order to satisfy a dependency of Gnome Boxes.

**Comment by fubhy** [comment]
Same issue with libvirt too (e.g. when developing locally with minishift / minikube). I honestly think that instead of advocating for pygmy, there should be a section for how to run the local dev env for amazeeio without pygmy. Pygmy is really not THAT necessary and it's just a convenience tool that sets up everything automatically (dns, ssh keys, etc.). I am actually wondering if it would be better to just show the manual installation steps as the default?

**Comment by back-2-95** [comment]
Any new development on this?
Ubuntu and it's different versions seem to be very difficult with this one...

**Comment by dasrecht** [comment]
We rolled out a functionality with pygmy 0.9.9 `pygmy up --no-resolver` which will not start a resolver. When this is used you basically need to overwrite the sites you use locally in your `/etc/hosts` file.
