### ISSUE TITLE
Docker Compose v2 support

### ISSUE THREAD

**Issue by christopher-hopper** [pygmystack/pygmy-legacy#60]
## Problem / Motivation

The pygmy tool breaks with the latest Docker Desktop where Docker Compose v2 support is enabled by default. 

## Steps to reproduce

1. Install Docker Desktop or update Docker Desktop
2. Open Docker Desktop Preferences 
3. On the General tab check to see that "Use Docker Compose V2" is enabled by default
4. Start pygmy by following the recommended steps
5. Start an Amazee.io Docker Compose local environment by following the recommended steps

**Comment by IvanZugec** [comment]
Can confirm that unchecking "Use Docker Composer V2" fixes the issue of `no such service: amazeeio-ssh-agent` appearing.

Would be useful to get the documentation change committed.

**Comment by fubarhouse** [comment]
Just a side note: https://github.com/docker/compose/issues/8874

**Comment by sonuku** [comment]
v2 is now GA

Any plans to move away from `volumes_from`? It's been deprecated for a while now.

Maybe a named external?

**Comment by tobybellwood** [comment]
Not technically a pygmy issue - but I've heard rumours this is now handled better in newer versions of docker bundled with docker desktop
